import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url);let ts;try{ts=require('typescript');}catch{ts=require(path.join(execFileSync('npm',['root','-g'],{encoding:'utf8'}).trim(),'typescript'));}
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const cfgFile=path.join(root,'tsconfig.driver.json');const config=ts.readConfigFile(cfgFile,ts.sys.readFile);if(config.error)throw Error(ts.flattenDiagnosticMessageText(config.error.messageText,'\n'));
const parsed=ts.parseJsonConfigFileContent(config.config,ts.sys,root);const program=ts.createProgram(parsed.fileNames,parsed.options);const emitted=program.emit();const errors=[...parsed.errors,...ts.getPreEmitDiagnostics(program),...emitted.diagnostics].filter(d=>d.category===ts.DiagnosticCategory.Error);if(errors.length)throw Error(ts.formatDiagnosticsWithColorAndContext(errors,{getCanonicalFileName:p=>p,getCurrentDirectory:()=>root,getNewLine:()=>'\n'}));
const dir=path.join(root,'public/driver-foundation'),legacy=path.join(root,'public/pose-v5'),modules=path.join(dir,'modules');
fs.mkdirSync(modules,{recursive:true});fs.writeFileSync(path.join(modules,'package.json'),'{"type":"module"}\n');
const assets={};for(const n of ['atlas.json','skin-weights.json'])assets[n]=fs.readFileSync(path.join(legacy,n),'utf8');
const atlas=JSON.parse(assets['atlas.json']);for(const n of [...atlas.parts.map(p=>p.src),...['canon-1','canon-2','canon-3','canon-4']]){const b=fs.readFileSync(path.join(legacy,n));assets[n]='data:'+(b[0]===137?'image/png':b.toString('ascii',0,4)==='RIFF'?'image/webp':'image/jpeg')+';base64,'+b.toString('base64');}
for (const n of ['e0628ddf8c351b3b9425.png','48ba4faf9045baac59c6.png','cff7d8f7da882463c78b.png']) {
  const b=fs.readFileSync(path.join(root,'public/catalog-views',n));
  assets['catalog/'+n]='data:image/png;base64,'+b.toString('base64');
}
assets['catalog-index.json']=fs.readFileSync(path.join(root,'public/catalog/index.json'),'utf8');
assets['qc-blocks.json']=fs.readFileSync(path.join(root,'public/catalog/qc-blocks.json'),'utf8');
const assetSetId='seed-v5-'+crypto.createHash('sha256').update(JSON.stringify(assets)).digest('hex');
fs.writeFileSync(path.join(dir,'assets.json'),JSON.stringify({assetSetId,assets}));
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
const factories=walk(modules).filter(p=>p.endsWith('.js')).map(p=>{const id=path.relative(modules,p).replaceAll('\\','/');const code=ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;return JSON.stringify(id)+':function(require,module,exports){\n'+code+'\n}';}).join(',\n');
const runtime=`const factories={${factories}},cache={};function get(id){if(cache[id])return cache[id].exports;if(!factories[id])throw Error('Missing module '+id);const m={exports:{}};cache[id]=m;const req=(p)=>{const parts=(id.split('/').slice(0,-1).join('/')+'/'+p).split('/'),out=[];for(const v of parts){if(v==='.'||!v)continue;if(v==='..')out.pop();else out.push(v);}return get(out.join('/'));};factories[id](req,m,m.exports);return m.exports;}`;
const css=fs.readFileSync(path.join(dir,'style.css'),'utf8');
const html=`<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="dark"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data: blob:; connect-src 'none'"><title>Shadowveil · Screen Labels 0.1.2</title><style>${css}</style></head><body><div id="app">Loading the character project…</div><script>(()=>{'use strict';${runtime}\nconst assets=${JSON.stringify(assets).replaceAll('<','\\u003c')};get('driver/app.js').mount(document.getElementById('app'),{assets,assetSetId:${JSON.stringify(assetSetId)}}).then(api=>{window.characterDriver=api;window.driverReady=true;}).catch(e=>{document.getElementById('app').textContent='Unable to load: '+e.message;console.error(e);});})();</script></body></html>`;
const out=path.join(root,'Shadowveil_Character_Driver_Foundation.html');fs.writeFileSync(out,html);fs.writeFileSync(path.join(dir,'index.html'),html);fs.writeFileSync(path.join(root,'build-manifest.json'),JSON.stringify({version:'foundation-0.1.2',assetSetId,htmlSha256:crypto.createHash('sha256').update(html).digest('hex'),legacySourceHash:atlas.source_sha256,standaloneBytes:Buffer.byteLength(html)},null,2));
console.log('Built',out,Buffer.byteLength(html),'bytes');
